import './globals.css';
import { Space_Mono } from 'next/font/google';

const spaceMono = Space_Mono({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Calculator</title>
      </head>
      <body
        className={`${spaceMono.className} bg-[#C8E8E8] text-[#00474B] h-screen flex justify-center items-center`}
      >
        <div className="absolute top-16 w-full flex justify-center items-center font-bold text-xl">
          <span className="w-24 grid place-items-center grid-rows-2 grid-cols-5 gap-x-4">
            <p>C</p>
            <p>A</p>
            <p>L</p>
            <p>C</p>
            <p>U</p>
            <p>L</p>
            <p>A</p>
            <p>T</p>
            <p>O</p>
            <p>R</p>
          </span>
        </div>
        <main className="flex-1 max-w-2xl px-2 sm:px-4">
          <section className="bg-white w-full rounded-xl shadow-xl p-4">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
